
### Grubbs Test for Determining an Outlier

The Grubbs test is used to determine if there are any outliers in a data set.
There is no agreed formal definition for an outlier. The definition of outlier used for this procedure is a value that unusually distance from the rest of the values.\\  (For the sake of clarity , we shall call this type of outlier a \textbf{Grubbs Outlier}).\\ Consider the following data set: is the lowest value 4.01 an outlier?

<pre><code>
6.98 8.49 7.97 6.64
8.80 8.48 5.94 6.94
6.89 7.47 7.32 4.01
</code></pre>

Under the null hypothesis, there are no outliers present in the data set. 
We reject this hypothesis if the p-value is sufficiently small.
(Remark: This is a one-tailed test).


<p>

### Grubbs Test for Determining an Outlier

<pre><code>
> grubbs.test(x, two.sided=T)
Grubbs test for one outlier
data: x
G = 2.4093, U = 0.4243, p-value = 0.05069
alternative hypothesis: lowest value 4.01 is an outlier
</code></pre>

We dont not have enough evidence to class 4.01 as an outlier.
We conclude that while small by comparison to the other values, the lowest value 4.01 is not an outlier.
