---
title: The Chi-Squared Test - Worked Example
subtitle: Early Childhood Intervention Program
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{css my-header-colors, echo = FALSE}
.page-header {
    background-image: linear-gradient(120deg, lightgreen, orange);
}
```

## Example

Consider a hypothetical experiment on the effectiveness of early childhood intervention programs:

- In the experimental group, 73 out of 85 students graduated from high school.
- In the control group, only 43 out of 82 students graduated.
- These data are depicted in the contingency table shown below.

---

## Chi-Square Test for Goodness of Fit

The chi-squared test applied to contingency tables.

The Chi-squared test is the most commonly used test for frequency data and goodness-of-fit. In theory, it is nonparametric but because it has no parametric equivalent, it is not classified as such. It is not an exact test and with the current level of computing facilities, there is not much excuse not to use Fisher’s exact test for \(2 \times 2\) contingency table analysis instead of the Chi-squared test.

### Example

Consider a hypothetical experiment on the effectiveness of early childhood intervention programs:
- In the experimental group, 73 out of 85 students graduated from high school.
- In the control group, only 43 out of 82 students graduated.
- The data can be depicted in a contingency table as follows:

## Chi-Square Test for Goodness of Fit

The chi-squared test applied to contingency tables.

The Chi-squared test is commonly used for frequency data and goodness-of-fit. While it is theoretically nonparametric, it has no parametric equivalent. It's not exact, and with current computing power, Fisher's exact test is preferred for \(2 \times 2\) contingency tables over the Chi-squared test.
