## Hypothesis test for the mean of a single sample 

This procedure is used to assess whether the population mean $\mu$  has a specified value, based on the sample mean. The hypotheses are conventionally written in a form similar to below (here the hypothesized population mean is simply zero).

       
       * [Ho] : $\mu = 0$
       * [Ha] : $\mu \neq 0$
       
There are two hypothesis test for the mean of a single sample.


 *  [1)] The sample is of a normally-distributed variable for which the population standard deviation ($\sigma$) is known.
 *  [2)] The sample is of a normally-distributed variable where $\sigma$ is estimated by the sample standard deviation (s).
In practice, the population parameter values is rarely known. For this reason, we will consider the second case only in this course.


### The \texttt{t.test()} Function}
The \texttt{t.test( )}function produces a variety of  outputs for procedures, hence answering such questions. Let us look at the function first to see what sort of output it gives us.
Recall our simulated data from last week, rolling a die 100 times.


<pre><code>
## Initialize variables
die = 1:6
N=100

## Calculations
x=sample(die,N, replace=TRUE)
t.test(x)
</code></pre>

The <tt>R</tt> output should look something like this:
<pre><code>
One Sample t-test
data:  x
t = 19.8867, df = 99, p-value < 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 3.087767 3.772233
sample estimates:
mean of x :     3.43
</code></pre>

Working backwards, the t procedure gives us the mean of the data set, and a $95\%$ confidence interval for that mean.  (Please refer to previous modules)

The previous statement to these refers to the alternative hypothesis: true mean is not equal to zero. Necessarily the null hypothesis (which proposes the opposite of the alternative hypothesis) states that the true mean is zero.
Is this meaningful in such circumstances? No, it is impossible

Let’s look at the help file to get a clearer idea about how to use this command.

The default setting of the null value is zero (i.e. <tt>mu = 0}}. To assess whether our data set is fair, we must specify <tt>mu = 3.5}}.

We can change the confidence level (and by extension,  the significance level)  by specifying the desired value using the <tt>conf.level = …}}.

In this instance, we will change it to 0.99 ( i.e. $99\%$ confidence). However for the rest of the module, we will use the $95\%$ confidence level. (Remark: Be mindful that I might ask this in the exam.).


<pre><code>
t.test(x,mu=3.5,conf.level=0.99)
</code></pre>


<pre><code>
One Sample t-test
data:  x
t = -0.4059, df = 99, p-value = 0.6857
alternative hypothesis: true mean is not equal to 3.5
99 percent confidence interval:
 2.977004 3.882996
sample estimates:
mean of x
     3.43
</code></pre>
The mean value remains constant. We have specified a $99\%$ confidence level, so necessarily a $99\%$ confidence interval is returned. Compare it to the previous output.

The important difference is what is specified as the alternative hypothesis: <tt>true mean is not equal to 3.5}}. Necessarily the null hypothesis is that true mean is equal to 3.5 (i.e. a fair dice). This is meaningful in the contest of the dice-roll experiment.

In this instance the p-value is 0.6857. We fail to reject the null hypothesis that the mean is not 3.5.
We can use the confidence interval to make an inference. Consider the $95\%$ confidence interval for the mean value (from earlier) : \texttt{(3.087767,3.4372233)}

As the expected mean (i.e. the null value) is within this interval, we would fail to reject the null hypothesis.
Suppose the $95\%$ confidence interval returned the following limits, with other values being computed accordingly; \texttt{(3.087767,3.4372233)}.

What would be the decision in this case? We would reject the null hypothesis that the mean value is 3.5, and surmise that the dice is a crooked dice that favours lower values.
